export const CHARACTERS_GET = "CHARACTERS_GET";
export const CHARACTERS_GET_REQUEST = "CHARACTERS_GET_REQUEST";
export const CHARACTERS_GET_SUCCESS = "CHARACTERS_GET_SUCCESS";
export const CHARACTERS_GET_FAILURE = "CHARACTERS_GET_FAILURE";
